server:
  port: 9102
spring:
  application:
    name: gamesc-pay
  datasource:
    url: jdbc:mysql://10.7.125.142:3306/plat_order_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: odao@wyz123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
      # filters: stat,wall,log4j,config  # stat是统计，wall是SQL防火墙，防SQL注入的，log4j是用来输出统计数据的
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow: 127.0.0.1 #IP 白名单
        url-pattern: /druid/* #监控地址,默认 /druid/*
        login-username: douzi
        login-password: admin123
  redis:
    database: 5
    lettuce:
      pool:
        max-active: 16
        max-wait: 5
        max-idle: 5
        min-idle: 5
    host: 10.7.125.142
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://10.7.51.61:10089/eureka
  instance:
    prefer-ip-address: true
    ip-address: 10.7.51.61
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info