server:
  port: 9999
  servlet:
    context-path: /api #服务端口
spring:
  application:
    name: gamesc-zuul #指定服务名
  redis:
    host: 10.7.125.142
    port: 6379
    database: 6
    password: 123456
    lettuce:
      pool:
        max-active: 16
        max-wait: 5
        max-idle: 5
        min-idle: 5
zuul:
  routes:
    exchange-web:
          path: /exchange/**
          serviceId: gamesc-exchange-web
  retryable: true
  sensitive-headers: #请求头跨系统发送token秘钥
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 50000
    connection-request-timeout-millis: 50000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  eager-load:
    enabled: true
    clients: gamesc-exchange-web
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://10.7.125.237:10089/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /api/actuator/health #网关设置了根路径，默认监控路径发生了变化
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


